spring:
  application:
    name: seek-challenge
  datasource:
    url: jdbc:mysql://localhost:3306/candidates_db?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:candidate-user}
    password: ${MYSQL_PASSWORD:uno-muy-dificil}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
